### ISSUE TITLE
Attaching a monitor while screen is locked reveals desktop

### ISSUE THREAD

**Issue by twvd** [regolith-linux/regolith-desktop#455]
**Describe the bug**
When a monitor is attached while the screen is locked, the lock screen will stick on one monitor, but the other one will show one of the i3 workspaces. You can look at it, but not interact with it.

**To Reproduce**
Lock screen, attach second monitor. Detaching and attaching again will show different workspaces each time.

**Expected behavior**
Attaching a second monitor does not reveal contents of a workspace.

**Configuration file(s)**
No customizations in place.

**Installation Details**
 - Regolith Install Type: PPA
 - Regolith Version: 1.4.1
 - PPA url: ppa:regolith-linux/release
 - Host OS (for PPA): Ubuntu 20.04

**Comment by moritzheiber** [comment]
@twvd Can you go a little bit more into detail what you're hardware setup looks like? Machine you're attaching this monitor to, technology for connecting the monitor (HDMI etc.)

FYI, this is likely a `gnome-flashback` issue, which Regolith cannot really fix, but I want to make sure to get a better understanding of the situation before forwarding it upstream.

Please also tell me about the version of `gnome-flashback` that's installed on your system (`apt policy gnome-flashback`).

**Comment by twvd** [comment]
It's a laptop with an external monitor attached (DisplayPort). The secondary monitor is introduced by opening the laptop and therefore activating the builtin display.

gnome-flashback version: 3.36.3-0ubuntu1.

**Comment by muktupavels** [comment]
https://gitlab.gnome.org/GNOME/gnome-flashback/-/commit/cdc534a3b0f4abe4e02a5397466ae094ee3d7fdc

I think that should fix this problem.

**Comment by moritzheiber** [comment]
@muktupavels Is there an ETA for another `gnome-flashback` release to `focal-proposed`?

**Comment by muktupavels** [comment]
No. First someone should verify that fixes actually work. Then I will cherry-pick fixes to gnome-3-36 branch.

If someone wants to see update in focal, I will make new release. Then someone (I don't plan to do that) will need to create SRU bug in launchpad.net - https://wiki.ubuntu.com/StableReleaseUpdates#SRU_Bug_Template.

**Comment by twvd** [comment]
Thanks, that was quick! I'll see if I can test your fix during the week.

**Comment by twvd** [comment]
> https://gitlab.gnome.org/GNOME/gnome-flashback/-/commit/cdc534a3b0f4abe4e02a5397466ae094ee3d7fdc
> 
> I think that should fix this problem.

I applied this commit on top of the current ubuntu package source for gnome-flashback and that indeed fixes the problem for me!

Sometimes i3bar still appears on the lock screen, but that's a minor detail I guess. At least workspace contents are not shown anymore now.

**Comment by muktupavels** [comment]
It could be i3bar or window manager problem... I have not seen gnome-panel on lock screen with metacity.

**Comment by kgilmer** [comment]
@muktupavels thanks for your help!  Regarding the SRU process, it looks (understandably) like a lot of work.  It's unclear to me if Ubuntu would recognize that a Regolith bug applies to Ubuntu as a whole, as it appears that a QA will validate the fix.  Would hosting an updated build of gnome-flashback in Regolith PPAs be an acceptable workaround to SRU or you suggest following the process?

**Comment by muktupavels** [comment]
SRU uploads are reviewed and either accepted or rejected. If accepted then upload will be available in proposed for testing.  Testing/validation is done by users.

Of course you can add patches to gnome-flashback and upload to your PPA. But I guess it would be nicer to get fixes in Ubuntu for all users.

**Comment by eduncan911** [comment]
Thank you for posting this issue!  It's been driving me crazy with my multi-monitor + multi-docking stations + a 3rd monitor setup I constantly switch between.  Yes, I run and switch between four completely different "multi-monitor/dockingstations w/display/hdmi ports" setups!  The exact same problem happens on all of them.  So it's not unique to them - which are extremely different setups.

However, what the OP hasn't described though is a related issue I am suffering from. It may be fixed with the same commit, let me put it here - and let me know if it needs to be a different Issue:

Same "screen shows while locked" problem the OP describes.  Except, I can't do anything.  I can't login, I can unlock.  I can't suspend/sleep/etc.  I loose total control over my system.  It happens when I "undock/unplug" when the system is on and has been docked/connected to external monitors.  

I can use my mouse to move the pointer around the screen, which I can see my previous desktop before it was locked.  But I cannot click, can't change screens/sessions, etc.  I cannot do anything, as though it was "locked" - but i can see the desktop.  _Even the i3bar continues to update_!  I just can't click, nor type anything - nor login (as though hidden maybe).  Nothing.  No power button combinations.  No suspend.  Nothing.

The only, and I mean only way out, is a HARD RESET of the entire machine (hold power button for 4 seconds).  It's that bad.

---

My work arounds until it is patched (which sounds like we may have found it? and hopefully it fixed my problem too) was when I knew I would be disconnecting sometime soon, or in the morning, or when I know I was going to jump in the car (etc), I would have always have to "prepare" the system before I made such a drastic change:

* unlock and log into the system
* undock/remove thunder3 cable/remove HDMI adapters/remove DP adapters/etc etc
* wait for the monitor screen to refresh
* re-lock/suspend

...and then I could walk away and come back to grab the laptop when I was ready to leave.

On the other hand, if something changed and I needed to just "leave", it was impossible to do without unlocking first and running through the procedures above.

As I am writing this, my thunderbolt 3 cable became loose.  This effectively "undocked" the laptop while it was locked.  I am completely locked out, again, showing my desktop.  My only option, is a hard reset of the system.  :(

Finally decided to come looking, and found this issue.  Which may improve my experience.

Any ETA on the release?  :) I apply all Regolith updates via aptitude regularly.

**Comment by twvd** [comment]
@eduncan911 when you face that issue, is your screen locked? If so, have you tried entering your password blindly? I recall a similar thing and I think that worked.

For now I started using i3lock-fancy as a lock screen with xautolock, that works fine for me. Added advantage of that for me is I can get dunst to show notifications on the lock screen and lock the system without the monitor turning black. i3lock seems more stable and it handles any monitor configuration change just fine.

**Comment by eduncan911** [comment]
@twvd yeah, that was a lot of text.  i did mention I cannot login:

> I just can't click, nor type anything - nor login (as though hidden maybe)

yes, i type blindly thinking maybe there's a prompt.  but nope, nothing happens after pressing enter.

my i3-fu is about 6 years old... remind me of how to switch to `i3lock-fancy`?  :)

**Comment by muktupavels** [comment]
There is no ETA but I will try to make new release when I have more time. Please create launchpad.net bug (ideally already using SRU template!).

**Comment by twvd** [comment]
@eduncan911 sorry, missed that bit :)

For i3lock, install xautolock and i3lock-fancy. Disable the GNOME lock screen.

Add to .xsession:
`/usr/bin/xautolock -time 5 -locker /usr/bin/i3lock-fancy -secure &`

Add to .Xresources-regolith:
`i3-wm.program.lock: /usr/bin/xautolock -locknow`

Then logout and your screen will lock after 5 minutes or on the normal lock shortcut key.

**Comment by twvd** [comment]
@muktupavels who is supposed to make that launchpad request? Me, as reporter (I wouldn't have a clue personally :) ), someone from the Regolith crew or you, as gnome-flashback dev?

I also saw someone have this same issue on Linux Mint, so the bug is not just regolith specific.

**Comment by muktupavels** [comment]
Anyone who can reproduce problem, is ready to spend time creating bug and then verify fix once upload will be accepted in proposed. Bug must use SRU template and I think anyone should be able to fill needed things except `[Regression Potential]`.

https://bugs.launchpad.net/ubuntu/+source/gnome-flashback/+filebug
https://wiki.ubuntu.com/StableReleaseUpdates#SRU_Bug_Template

As `gnome-flashback` dev I mostly care only about development/next version... And only "supported" version is last stable release. I have no time for anything else.

**Comment by eduncan911** [comment]
> @muktupavels As gnome-flashback dev I mostly care only about development/next version... And only "supported" version is last stable release. I have no time for anything else.

Thanks for clarifying that!  It's often that developers do not think about supporting product lines (aka version branches/tags) for X number of years, patching previous releases, after they write code.  I deal with this on a daily basis at my gig, with over a dozen products and nearly 100 versions that need to be supported for X timelines.  For those wondering WTH I am talking about, think about Ubuntu's well established release cycle with their 5-year LTS (and even more, when paying for Live Patching):

https://ubuntu.com/about/release-cycle

Having someone know the options, and clearly make a commitment (only forward, plus one old) is a big relief as to how this product will progress overtime.  :)  Maybe put that in some form of FAQs or make it more prominent, as I am sure I am not the only one thinking this.

But I agree, there's no reason to support older versions - unless it was included in mainline (then it would have to be) as mainline only accepts security and bug patches during it's LTS phase.

**Comment by twvd** [comment]
Launchpad bug opened: https://bugs.launchpad.net/ubuntu/+source/gnome-flashback/+bug/1891855

**Comment by twvd** [comment]
Ubuntu has released the update for gnome-flashback so this is closed I guess.

**Comment by kgilmer** [comment]
Thank you for the follow up @twvd !
